version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=chatdb
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app:
    build: .
    command: ./entrypoint.sh
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      # For dev purposes
      - .:/app
    depends_on:
      - db
